import { useState } from "react";
import Card from '../components/movie/Card';


export default function Movies() {
    const API_URL = import.meta.env.VITE_MOVIE_APP_URL;
    const API_KEY = import.meta.env.VITE_MOVIE_API_KEY;
    const featuredMovies = [
        { "Title": "The Covenant", "Year": "2023", "Rated": "R", "Released": "21 Apr 2023", "Runtime": "123 min", "Genre": "Action, Drama, Thriller", "Director": "Guy Ritchie", "Writer": "Guy Ritchie, Ivan Atkinson, Marn Davies", "Actors": "Jake Gyllenhaal, Dar Salim, Sean Sagar", "Plot": "During the war in Afghanistan, a local interpreter risks his own life to carry an injured sergeant across miles of grueling terrain.", "Language": "English, Dari", "Country": "United Kingdom, Spain, United States", "Awards": "N/A", "Poster": "https://m.media-amazon.com/images/M/MV5BNmQzOWZhOTMtZTcxNC00MTdkLWEwYmUtOWVmOTFhNTdkNjRkXkEyXkFqcGdeQXVyODk2NDQ3MTA@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "7.5/10" }, { "Source": "Metacritic", "Value": "63/100" }], "Metascore": "63", "imdbRating": "7.5", "imdbVotes": "136,407", "imdbID": "tt4873118", "Type": "movie", "DVD": "N/A", "BoxOffice": "$16,938,039", "Production": "N/A", "Website": "N/A", "Response": "True" },
        { "Title": "Dahmer", "Year": "2002", "Rated": "R", "Released": "13 Mar 2003", "Runtime": "101 min", "Genre": "Biography, Crime, Drama", "Director": "David Jacobson", "Writer": "David Jacobson, David Birke", "Actors": "Jeremy Renner, Bruce Davison, Artel Great", "Plot": "Biopic about notorious American serial killer Jeffrey Dahmer, taking place in both the past and the present.", "Language": "English", "Country": "United States", "Awards": "3 nominations", "Poster": "https://m.media-amazon.com/images/M/MV5BZmQ0NzYyM2ItMzU2Yy00NDA0LWIzYjAtMjg3Y2Y1NmQ0MWFiXkEyXkFqcGdeQXVyMzU4ODM5Nw@@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "5.6/10" }, { "Source": "Rotten Tomatoes", "Value": "73%" }, { "Source": "Metacritic", "Value": "63/100" }], "Metascore": "63", "imdbRating": "5.6", "imdbVotes": "11,498", "imdbID": "tt0285728", "Type": "movie", "DVD": "20 Jan 2017", "BoxOffice": "$144,008", "Production": "N/A", "Website": "N/A", "Response": "True" },
        { "Title": "Batman", "Year": "1989", "Rated": "PG-13", "Released": "23 Jun 1989", "Runtime": "126 min", "Genre": "Action, Adventure", "Director": "Tim Burton", "Writer": "Bob Kane, Sam Hamm, Warren Skaaren", "Actors": "Michael Keaton, Jack Nicholson, Kim Basinger", "Plot": "The Dark Knight of Gotham City begins his war on crime with his first major enemy being Jack Napier, a criminal who becomes the clownishly homicidal Joker.", "Language": "English, French, Spanish", "Country": "United States, United Kingdom", "Awards": "Won 1 Oscar. 10 wins & 28 nominations total", "Poster": "https://m.media-amazon.com/images/M/MV5BZWQ0OTQ3ODctMmE0MS00ODc2LTg0ZTEtZWIwNTUxOGExZTQ4XkEyXkFqcGdeQXVyNzAwMjU2MTY@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "7.5/10" }, { "Source": "Rotten Tomatoes", "Value": "76%" }, { "Source": "Metacritic", "Value": "69/100" }], "Metascore": "69", "imdbRating": "7.5", "imdbVotes": "396,849", "imdbID": "tt0096895", "Type": "movie", "DVD": "24 Jul 2014", "BoxOffice": "$251,409,241", "Production": "N/A", "Website": "N/A", "Response": "True" },
        { "Title": "Iron Man", "Year": "2008", "Rated": "PG-13", "Released": "02 May 2008", "Runtime": "126 min", "Genre": "Action, Adventure, Sci-Fi", "Director": "Jon Favreau", "Writer": "Mark Fergus, Hawk Ostby, Art Marcum", "Actors": "Robert Downey Jr., Gwyneth Paltrow, Terrence Howard", "Plot": "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.", "Language": "English, Persian, Urdu, Arabic, Kurdish, Hindi, Hungarian", "Country": "United States, Canada", "Awards": "Nominated for 2 Oscars. 22 wins & 73 nominations total", "Poster": "https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "7.9/10" }, { "Source": "Rotten Tomatoes", "Value": "94%" }, { "Source": "Metacritic", "Value": "79/100" }], "Metascore": "79", "imdbRating": "7.9", "imdbVotes": "1,102,172", "imdbID": "tt0371746", "Type": "movie", "DVD": "01 Mar 2013", "BoxOffice": "$319,034,126", "Production": "N/A", "Website": "N/A", "Response": "True" },
        { "Title": "The Fast and the Furious", "Year": "2001", "Rated": "PG-13", "Released": "22 Jun 2001", "Runtime": "106 min", "Genre": "Action, Crime, Thriller", "Director": "Rob Cohen", "Writer": "Ken Li, Gary Scott Thompson, Erik Bergquist", "Actors": "Vin Diesel, Paul Walker, Michelle Rodriguez", "Plot": "Los Angeles police officer Brian O'Conner must decide where his loyalty really lies when he becomes enamored with the street racing world he has been sent undercover to destroy.", "Language": "English, Spanish", "Country": "United States, Germany", "Awards": "11 wins & 18 nominations", "Poster": "https://m.media-amazon.com/images/M/MV5BNzlkNzVjMDMtOTdhZC00MGE1LTkxODctMzFmMjkwZmMxZjFhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "6.8/10" }, { "Source": "Rotten Tomatoes", "Value": "54%" }, { "Source": "Metacritic", "Value": "58/100" }], "Metascore": "58", "imdbRating": "6.8", "imdbVotes": "409,850", "imdbID": "tt0232500", "Type": "movie", "DVD": "10 Sep 2015", "BoxOffice": "$144,745,925", "Production": "N/A", "Website": "N/A", "Response": "True" },
        { "Title": "2012", "Year": "2009", "Rated": "PG-13", "Released": "13 Nov 2009", "Runtime": "158 min", "Genre": "Action, Adventure, Sci-Fi", "Director": "Roland Emmerich", "Writer": "Roland Emmerich, Harald Kloser", "Actors": "John Cusack, Thandiwe Newton, Chiwetel Ejiofor", "Plot": "A frustrated writer struggles to keep his family alive when a series of global catastrophes threatens to annihilate mankind.", "Language": "English, French, Tibetan, Mandarin, Russian, Hindi, Portuguese, Latin, Italian, Spanish", "Country": "United States", "Awards": "5 wins & 21 nominations", "Poster": "https://m.media-amazon.com/images/M/MV5BMTY0MjEyODQzMF5BMl5BanBnXkFtZTcwMTczMjQ4Mg@@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "5.8/10" }, { "Source": "Rotten Tomatoes", "Value": "39%" }, { "Source": "Metacritic", "Value": "49/100" }], "Metascore": "49", "imdbRating": "5.8", "imdbVotes": "391,459", "imdbID": "tt1190080", "Type": "movie", "DVD": "01 Apr 2010", "BoxOffice": "$166,112,167", "Production": "N/A", "Website": "N/A", "Response": "True" },
        { "Title": "The Office", "Year": "2005–2013", "Rated": "TV-14", "Released": "24 Mar 2005", "Runtime": "22 min", "Genre": "Comedy", "Director": "N/A", "Writer": "Greg Daniels, Ricky Gervais, Stephen Merchant", "Actors": "Steve Carell, Jenna Fischer, John Krasinski", "Plot": "A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.", "Language": "English, Spanish, German, French", "Country": "United States", "Awards": "Won 5 Primetime Emmys. 51 wins & 195 nominations total", "Poster": "https://m.media-amazon.com/images/M/MV5BMDNkOTE4NDQtMTNmYi00MWE0LWE4ZTktYTc0NzhhNWIzNzJiXkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "9.0/10" }], "Metascore": "N/A", "imdbRating": "9.0", "imdbVotes": "675,177", "imdbID": "tt0386676", "Type": "series", "totalSeasons": "9", "Response": "True" },
        { "Title": "Fury", "Year": "2014", "Rated": "R", "Released": "17 Oct 2014", "Runtime": "134 min", "Genre": "Action, Drama, War", "Director": "David Ayer", "Writer": "David Ayer", "Actors": "Brad Pitt, Shia LaBeouf, Logan Lerman", "Plot": "A grizzled tank commander makes tough decisions as he and his crew fight their way across Germany in April, 1945.", "Language": "English, German", "Country": "United States, China, United Kingdom", "Awards": "5 wins & 23 nominations", "Poster": "https://m.media-amazon.com/images/M/MV5BMjA4MDU0NTUyN15BMl5BanBnXkFtZTgwMzQxMzY4MjE@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "7.6/10" }, { "Source": "Rotten Tomatoes", "Value": "76%" }, { "Source": "Metacritic", "Value": "64/100" }], "Metascore": "64", "imdbRating": "7.6", "imdbVotes": "527,913", "imdbID": "tt2713180", "Type": "movie", "DVD": "04 Feb 2016", "BoxOffice": "$85,817,906", "Production": "N/A", "Website": "N/A", "Response": "True" },
        { "Title": "Uncharted", "Year": "2022", "Rated": "PG-13", "Released": "18 Feb 2022", "Runtime": "116 min", "Genre": "Action, Adventure", "Director": "Ruben Fleischer", "Writer": "Rafe Judkins, Art Marcum, Matt Holloway", "Actors": "Tom Holland, Mark Wahlberg, Antonio Banderas", "Plot": "Street-smart Nathan Drake is recruited by seasoned treasure hunter Victor \"Sully\" Sullivan to recover a fortune amassed by Ferdinand Magellan, and lost 500 years ago by the House of Moncada.", "Language": "English, Spanish", "Country": "United States, Spain", "Awards": "1 nomination", "Poster": "https://m.media-amazon.com/images/M/MV5BMWEwNjhkYzYtNjgzYy00YTY2LThjYWYtYzViMGJkZTI4Y2MyXkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "6.3/10" }, { "Source": "Metacritic", "Value": "45/100" }], "Metascore": "45", "imdbRating": "6.3", "imdbVotes": "239,809", "imdbID": "tt1464335", "Type": "movie", "DVD": "N/A", "BoxOffice": "$148,648,820", "Production": "Columbia Pictures", "Website": "N/A", "Response": "True" },
        { "Title": "How It Ends", "Year": "2018", "Rated": "TV-MA", "Released": "13 Jul 2018", "Runtime": "113 min", "Genre": "Action, Drama, Horror", "Director": "David M. Rosenthal", "Writer": "Brooks McLaren", "Actors": "Theo James, Kat Graham, Nancy Sorel", "Plot": "In the midst of an apocalypse, a man struggles to reach his pregnant wife, who is thousands of miles away.", "Language": "English", "Country": "United States", "Awards": "5 nominations", "Poster": "https://m.media-amazon.com/images/M/MV5BMjMwOTg0MzU4MV5BMl5BanBnXkFtZTgwODk2NjY3NTM@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "5.0/10" }, { "Source": "Rotten Tomatoes", "Value": "17%" }, { "Source": "Metacritic", "Value": "36/100" }], "Metascore": "36", "imdbRating": "5.0", "imdbVotes": "56,546", "imdbID": "tt5246700", "Type": "movie", "DVD": "13 Jul 2018", "BoxOffice": "N/A", "Production": "N/A", "Website": "N/A", "Response": "True" },
        { "Title": "Code 8", "Year": "2019", "Rated": "Not Rated", "Released": "13 Dec 2019", "Runtime": "98 min", "Genre": "Action, Crime, Drama", "Director": "Jeff Chan", "Writer": "Chris Pare, Jeff Chan", "Actors": "Kari Matchett, Robbie Amell, Penny Eizenga", "Plot": "A super-powered construction worker falls in with a group of criminals in order to raise the funds to help his ill mother.", "Language": "English", "Country": "Canada", "Awards": "1 nomination", "Poster": "https://m.media-amazon.com/images/M/MV5BNmQ2NWMyZDgtNWQ5My00ZmQwLWE0MTQtN2ZiNjY2ODc0Y2YxXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "6.1/10" }, { "Source": "Rotten Tomatoes", "Value": "81%" }, { "Source": "Metacritic", "Value": "48/100" }], "Metascore": "48", "imdbRating": "6.1", "imdbVotes": "43,181", "imdbID": "tt6259380", "Type": "movie", "DVD": "13 Dec 2019", "BoxOffice": "N/A", "Production": "N/A", "Website": "N/A", "Response": "True" },
        { "Title": "Gladiator", "Year": "2000", "Rated": "R", "Released": "05 May 2000", "Runtime": "155 min", "Genre": "Action, Adventure, Drama", "Director": "Ridley Scott", "Writer": "David Franzoni, John Logan, William Nicholson", "Actors": "Russell Crowe, Joaquin Phoenix, Connie Nielsen", "Plot": "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.", "Language": "English", "Country": "United States, United Kingdom, Malta, Morocco", "Awards": "Won 5 Oscars. 60 wins & 104 nominations total", "Poster": "https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg", "Ratings": [{ "Source": "Internet Movie Database", "Value": "8.5/10" }, { "Source": "Rotten Tomatoes", "Value": "80%" }, { "Source": "Metacritic", "Value": "67/100" }], "Metascore": "67", "imdbRating": "8.5", "imdbVotes": "1,573,055", "imdbID": "tt0172495", "Type": "movie", "DVD": "15 Jun 2011", "BoxOffice": "$187,705,427", "Production": "N/A", "Website": "N/A", "Response": "True" }
    ];
    const [movies, setMovies] = useState([]);
    const [search, setSearch] = useState('');

    const searchMovies = async (title) => {
        const response = await fetch(`${API_URL}?apikey=${API_KEY}&s=${title}&plot=full`);
        const data = await response.json();
        if (data.Search) {
            setMovies(data.Search);
        } else {
            setMovies([]);
        }
    }

    return (
        <div className="mx-auto flex max-w-7xl pt-20 items-center flex-col justify-between p-6 lg:px-8">
            <label htmlFor="default-search" className="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
            <div className="relative mt-5 mb-5 w-full">
                <div className="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
                    <svg className="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                        <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
                    </svg>
                </div>
                <input
                    onChange={(e) => { setSearch(e.target.value) }}
                    value={search}
                    type="search"
                    id="default-search"
                    className="block w-full p-4 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                    placeholder="Search movies"
                    />
                <button
                    onClick={() => { searchMovies(search) }}
                    type="submit"
                    className="text-white absolute end-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Search</button>
            </div>

            {movies.length > 0 ? (
                <div className="cards--container grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-4">
                    {movies.map((movie) => (
                        <Card key={movie.imdbID} movie={movie} />
                    ))}
                </div>
            ) : (
                <div className="cards--container grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-4">
                    {featuredMovies.length && featuredMovies.map((movie) => (
                        <Card key={movie.imdbID} movie={movie} />
                    ))
                    }
                </div>
            )}
        </div>
    )
}